spring:
  application:
    name: employee-service
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
      url: jdbc:mysql://localhost:3306/dev1?useSSL=false
      username: root
      password: admin
      driverClassName: com.mysql.jdbc.Driver
server:
  port: 8085